# config.yaml

dnsdb:
#  api_key: "e5b359e398ba5b4b480bc5132c7278f6212c5ece7afaf82888b3eb67b09b18a5"
  base_url: "https://dnsdb.sie-europe.net/dnsdb/v2"
  default_limit: 5

misp:
  base_url: "https://misp.cert.dk"
#  api_key: "3WlyjnpsdRNLc3ZWPHyDYmmngrUOW3tdNbyh0sCd"
  verify_ssl: false

#otx:
#  api_key: "7f594b23a1adb69c0f8ffb5f654ccb5d230b59253cc0b237011e1388db710bd7"

defender:
  tenant_id: "a3927f91-cda1-4696-af89-8c9f1ceffa91"
  client_id: "5d65a56b-9af6-49b5-a2a6-eb364993802c"
  client_secret: "aDg8Q~i1sMMEn2BXSs21hu~lnXdniquCbZZlac52"
  scope: "https://api.security.microsoft.com/.default"
  token_url: "https://login.microsoftonline.com/a3927f91-cda1-4696-af89-8c9f1ceffa91/oauth2/v2.0/token"


logging:
  level: "INFO"
  log_to_file: false
  file_path: "logs/ioc_manager.log"



